config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  resources :products
  resources :order_items
  get 'cart', to: 'cart#show'
  get 'search', to: 'store#search'
  root 'store#index'
  get 'store', to: 'store#index'
  get 'info', to: 'pages#info'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal

  def subtotal
    order_items.collect {|item| item.valid? ? item.unit_price * item.quantity : 0 }.sum
  end

  private
  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  before_save :set_unit_price
  before_save :set_total

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total
    return quantity*unit_price
  end

  private
  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many :order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:heading, :body, :display)
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order
  def create
    @order_item = @order.order_items.new(order_params)
    @order.save

    session[:order_id] = @order.id
  end

  def update
    @order_item = @order.order_items.find(params[:id])
    @order_item.update(order_params)
    @order_items = current_order.order_items
  end

  def destroy
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy

    @order_items = current_order.order_items
    redirect_to cart_path
  end

  private
  def order_params
    params.require(:order_item).permit(:product_id, :quantity)
  end

  def set_order
    @order = current_order
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @page = 'home'
  end
  def info
    @page = 'info'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]
  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :image,  :price,  :collectibles, :pictures, :art, :sports, :available)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  before_action :set_category
  def index
    @page = 'store'
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def search
    query = params[:search]
    results = Product.where('name LIKE ?', "%#{query}%")

    if params[:filter] == 'Select Filter'
      @products = results
    else
      tag = params[:filter].gsub(/ /, '_').downcase!.to_sym
      @products = results.where(tag => true)
    end
  end

  private
  def set_category
    @cats = Category.all.where(display: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    if Order.find_by_id(session[:order_id]).nil?
      Order.new
    else
      Order.find_by_id(session[:order_id])
    end
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/cart/_cart.html.erb
<%= link_to "#{current_order.order_items.size} items in the cart with a total value of $#{current_order.subtotal}", cart_path%>

app/views/cart/_cart_items.html.erb
<% @order_items.each do |item| %>
  <hr>
  <div class="row">
    <%= image_tag(item.product.image, style:"max-height: 100px; max-width: 100px;") %>
    <h3><%= item.product.name%></h3>
    <span>
    <h4 style="color:gray; margin-left: 5px;">  $<%= item.product.price %></h4>
  <%= form_with model: item do |f|%>
    <%= link_to "Remove Items", item, method: :delete %>
  <% end%>
  </div>
  <h3>Subtotal: <%= item.total %></h3>
<% end %>
<hr>
<h2>Your order total: $<%= current_order.subtotal %></h2>

app/views/cart/show.html.erb
<div class="cart-item">
  <%= render 'cart_items' %>
</div>
<hr>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :heading %>
    <%= f.input :body %>
    <%= f.input :display %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Heading</th>
      <th>Body</th>
      <th>Display</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.heading %></td>
        <td><%= category.body %></td>
        <td><%= category.display %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Heading:</strong>
  <%= @category.heading %>
</p>

<p>
  <strong>Body:</strong>
  <%= @category.body %>
</p>

<p>
  <strong>Display:</strong>
  <%= @category.display %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_links.html.erb
<div class="col-2">
    <h5 class="link-container">
        <%= link_to "Store", root_path, class: "link #{@page == 'home' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "Inventory", products_path, class: "link #{@page == 'store' ? 'active' : ''}" %>
    </h5>
    <h5 class="link-container">
        <%= link_to "More Info", info_path, class: "link #{@page == 'info' ? 'active' : ''}" %>
    </h5>
    <% if current_user %>
      <h5 class="link-container">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "link active" %>
      </h5>

    <% else %>
      <h5 class="link-container">
          <%= link_to "Log In", new_user_session_path, class: "link active" %>
      </h5>
      <h5 class="link-container">
          <%= link_to "Sign Up", new_user_registration_path, class: "link active" %>
      </h5>
    <% end %>

</div>

app/views/layouts/_title.html.erb
<div class="title-card">
  <h1 class="title-text">
    ImageShop
  </h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="<%= @page %>-page">
      <div class="row page-container">
        <%= render 'layouts/links' %>
        <div class="col-8">
          <% unless @page == "home"%>
          <%= render 'layouts/title'%>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/order_items/create.html.erb
<h4>Your order has been added to your cart</h5>
<p><%= link_to "View Cart", cart_path%></p>
<p><%= link_to "Keep Shopping", root_path%></p>

app/views/order_items/destroy.js.erb
$("#cart").innerHTML = "<%= j render 'cart/cart' %>";
$("#cart-item").innerHTML = "<%= j render 'cart/cart_items' %>";

app/views/order_items/update.js.erb
$("#cart").innerHTML = "<%= j render 'cart/cart' %>";
$("#cart-item").innerHTML = "<%= j render 'cart/cart_items' %>";

app/views/pages/home.html.erb
<h1>
  Welcome to the ImageShop online store!
</h1>

app/views/pages/info.html.erb
<p>Hey guys, this is a sample application I built for the Shopify Backend Project.<p>
<p>This is an online marketplace where a user can buy images that are up for sale.</p>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>


  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :collectibles %>
    <%= form.check_box :collectibles %>
  </div>

  <div class="field">
    <%= form.label :pictures %>
    <%= form.check_box :pictures %>
  </div>

  <div class="field">
    <%= form.label :art %>
    <%= form.check_box :art %>
  </div>

  <div class="field">
    <%= form.label :sports %>
    <%= form.check_box :sports %>
  </div>

  <div class="field">
    <%= form.label :available %>
    <%= form.check_box :available %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<hr>
<h3>Add a new product </h3>
<%= link_to 'New Product', new_product_path, class: "btn btn-primary" %>
<hr>

<% @products.each do |product| %>
  <div style="padding: 5px;" >
    <div class="card" style="width: 18rem;">
      <a class="card-img-top" src="..." alt="card_image">
        <%= image_tag(product.image, style:"max-height: 100px; max-width: 100px;") %>
      </a>
      <div class="card-body">
        <h5 class="card-title"><%=product.name%></h5>
        <p class="card-text"><%=product.description%></p>
        <p class="card-text">$<%=product.price%></p>
        <%= link_to 'Show', product, class: "btn btn-primary"%>
        <%= link_to 'Edit', edit_product_path(product), class: "btn btn-primary" %>
        <%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
<% end %>

<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@product.image, class:'img-fluid') %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Collectibles:</strong>
  <%= @product.collectibles %>
</p>

<p>
  <strong>Pictures:</strong>
  <%= @product.pictures %>
</p>

<p>
  <strong>Art:</strong>
  <%= @product.art %>
</p>

<p>
  <strong>Sports:</strong>
  <%= @product.sports %>
</p>

<p>
  <strong>Available:</strong>
  <%= @product.available %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/store/_products.html.erb
<div class="row">
    <% if user_signed_in? == false %>
    <h2>Please log in or create an account to purchase.</h2>
    <% end %>

    <% @products.each do |product| %>
      <div class='col-4' style="padding: 5px;" >
        <div class="card" style="width: 18rem;">
          <a class="card-img-top" src="..." alt="card_image">
            <%= image_tag(product.image, class:'img-fluid', style: 'widht:150px;') %>
          </a>
          <div class="card-body">
            <h5 class="card-title"><%=product.name%></h5>
            <p class="card-text"><%=product.description%></p>
            <p class="card-text">$<%=product.price%></p>
            <% if user_signed_in? %>
                <%= form_with model: @order_item do |f| %>
                  <%= f.hidden_field :product_id, value: product.id %>
                  <%= f.number_field :quantity, value: 1, min: 1%>
                  <%= f.submit "Add to cart", class: "btn btn-primary" %>
                <% end %>
              <% end %>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/store/index.html.erb
<div class="store-container">
    <div id="store-products-container">
      <%= render 'store/products' %>
    </div>
</div>

<script>
  function clickSubmit() {
    console.log('key was pressed');
    document.getElementById("search_submit").click();
  }
</script>

app/views/store/search.js.erb
document.getElementById("store-products-container").innerHTML = "<%= j render 'store/products' %>";